CREATE DOMAIN D_COD_BARRA AS VARCHAR(255);

CREATE DOMAIN D_COD_FABRICANTE AS VARCHAR(255);

CREATE DOMAIN D_DATA AS DATE;

CREATE DOMAIN D_DATA_AGORA AS TIMESTAMP;

CREATE DOMAIN D_ENDERECO AS VARCHAR(255);

CREATE DOMAIN D_NOME AS VARCHAR(255);

CREATE DOMAIN D_NUMERO AS INTEGER;

CREATE DOMAIN D_PESO AS NUMERIC(15,6);

CREATE DOMAIN D_QTDADE AS NUMERIC(15,6);

CREATE DOMAIN D_QTDADE_NFE AS VARCHAR(255);

CREATE DOMAIN D_VALOR2 AS NUMERIC(15,2);

CREATE DOMAIN D_VALOR_UNITARIO_NFE AS VARCHAR(255);

CREATE DOMAIN D_VARCHAR255 AS VARCHAR(255);

CREATE DOMAIN D_ID AS CHAR(44) CHARACTER SET WIN1252 COLLATE WIN1252;

CREATE DOMAIN D_EMAIL AS VARCHAR(255) CHARACTER SET WIN1252 COLLATE WIN1252;

CREATE DOMAIN D_SMPT AS VARCHAR(255) CHARACTER SET WIN1252 COLLATE WIN1252;

CREATE DOMAIN D_SSL AS INTEGER;

CREATE DOMAIN D_TLS AS INTEGER;

CREATE EXCEPTION EX_UID_COLISAO 'COLISAO DE ID';

COMMENT ON EXCEPTION EX_UID_COLISAO IS 'COLISAO DE ID';