-- Teste com TBL0002
CREATE TABLE TBL0002 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0003
CREATE TABLE TBL0003 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0004
CREATE TABLE TBL0004 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0005
CREATE TABLE TBL0005 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0006
CREATE TABLE TBL0006 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0007
CREATE TABLE TBL0007 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0008
CREATE TABLE TBL0008 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0009
CREATE TABLE TBL0009 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0010
CREATE TABLE TBL0010 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0011
CREATE TABLE TBL0011 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0012
CREATE TABLE TBL0012 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0013
CREATE TABLE TBL0013 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0014
CREATE TABLE TBL0014 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0015
CREATE TABLE TBL0015 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0016
CREATE TABLE TBL0016 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0017
CREATE TABLE TBL0017 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0018
CREATE TABLE TBL0018 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0019
CREATE TABLE TBL0019 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0020
CREATE TABLE TBL0020 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0021
CREATE TABLE TBL0021 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0022
CREATE TABLE TBL0022 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0023
CREATE TABLE TBL0023 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0024
CREATE TABLE TBL0024 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0025
CREATE TABLE TBL0025 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0026
CREATE TABLE TBL0026 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0027
CREATE TABLE TBL0027 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0028
CREATE TABLE TBL0028 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0029
CREATE TABLE TBL0029 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0030
CREATE TABLE TBL0030 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0031
CREATE TABLE TBL0031 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0032
CREATE TABLE TBL0032 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0033
CREATE TABLE TBL0033 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0034
CREATE TABLE TBL0034 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0035
CREATE TABLE TBL0035 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0036
CREATE TABLE TBL0036 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0037
CREATE TABLE TBL0037 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0038
CREATE TABLE TBL0038 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0039
CREATE TABLE TBL0039 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0040
CREATE TABLE TBL0040 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0041
CREATE TABLE TBL0041 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0042
CREATE TABLE TBL0042 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0043
CREATE TABLE TBL0043 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0044
CREATE TABLE TBL0044 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0045
CREATE TABLE TBL0045 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0046
CREATE TABLE TBL0046 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0047
CREATE TABLE TBL0047 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0048
CREATE TABLE TBL0048 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0049
CREATE TABLE TBL0049 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0050
CREATE TABLE TBL0050 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0051
CREATE TABLE TBL0051 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0052
CREATE TABLE TBL0052 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0053
CREATE TABLE TBL0053 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0054
CREATE TABLE TBL0054 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0055
CREATE TABLE TBL0055 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0056
CREATE TABLE TBL0056 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0057
CREATE TABLE TBL0057 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0058
CREATE TABLE TBL0058 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0059
CREATE TABLE TBL0059 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0060
CREATE TABLE TBL0060 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0061
CREATE TABLE TBL0061 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0062
CREATE TABLE TBL0062 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0063
CREATE TABLE TBL0063 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0064
CREATE TABLE TBL0064 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0065
CREATE TABLE TBL0065 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0066
CREATE TABLE TBL0066 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0067
CREATE TABLE TBL0067 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0068
CREATE TABLE TBL0068 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0069
CREATE TABLE TBL0069 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0070
CREATE TABLE TBL0070 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0071
CREATE TABLE TBL0071 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0072
CREATE TABLE TBL0072 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0073
CREATE TABLE TBL0073 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0074
CREATE TABLE TBL0074 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0075
CREATE TABLE TBL0075 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0076
CREATE TABLE TBL0076 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0077
CREATE TABLE TBL0077 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0078
CREATE TABLE TBL0078 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0079
CREATE TABLE TBL0079 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0080
CREATE TABLE TBL0080 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0081
CREATE TABLE TBL0081 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0082
CREATE TABLE TBL0082 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0083
CREATE TABLE TBL0083 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0084
CREATE TABLE TBL0084 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0085
CREATE TABLE TBL0085 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0086
CREATE TABLE TBL0086 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0087
CREATE TABLE TBL0087 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0088
CREATE TABLE TBL0088 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0089
CREATE TABLE TBL0089 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0090
CREATE TABLE TBL0090 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0091
CREATE TABLE TBL0091 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0092
CREATE TABLE TBL0092 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0093
CREATE TABLE TBL0093 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0094
CREATE TABLE TBL0094 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0095
CREATE TABLE TBL0095 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0096
CREATE TABLE TBL0096 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0097
CREATE TABLE TBL0097 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0098
CREATE TABLE TBL0098 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0099
CREATE TABLE TBL0099 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0100
CREATE TABLE TBL0100 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0101
CREATE TABLE TBL0101 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0102
CREATE TABLE TBL0102 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0103
CREATE TABLE TBL0103 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0104
CREATE TABLE TBL0104 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0105
CREATE TABLE TBL0105 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0106
CREATE TABLE TBL0106 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0107
CREATE TABLE TBL0107 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0108
CREATE TABLE TBL0108 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0109
CREATE TABLE TBL0109 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0110
CREATE TABLE TBL0110 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0111
CREATE TABLE TBL0111 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0112
CREATE TABLE TBL0112 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0113
CREATE TABLE TBL0113 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0114
CREATE TABLE TBL0114 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0115
CREATE TABLE TBL0115 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0116
CREATE TABLE TBL0116 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0117
CREATE TABLE TBL0117 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0118
CREATE TABLE TBL0118 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;

-- Teste com TBL0119
CREATE TABLE TBL0119 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0,
  PRIMARY KEY (ID)
);
COMMIT;
