COMMENT ON TABLE TBL0001 IS 'Grupo de Usuarios';
COMMENT ON TABLE TBL0002 IS 'SMTP';
COMMENT ON TABLE TBL0003 IS 'Usuarios';
COMMENT ON TABLE TBL0004 IS 'Modulos Sistema';
COMMENT ON TABLE TBL0005 IS 'Opcao do Sistema';
COMMENT ON TABLE TBL0006 IS 'Grupo x Opcao Sistema';
COMMENT ON TABLE TBL0007 IS 'Atividade';
COMMENT ON TABLE TBL0008 IS 'Forma de Pagamento';
COMMENT ON TABLE TBL0009 IS 'Dias Forma de Pagamento';
COMMENT ON TABLE TBL0010 IS 'Tabela de Preco';
COMMENT ON TABLE TBL0011 IS 'Produtos Tabela Preco';
COMMENT ON TABLE TBL0012 IS 'TBL0012'; -- Descrição não fornecida, mantido o nome da tabela
COMMENT ON TABLE TBL0013 IS 'Zonas de Venda';
COMMENT ON TABLE TBL0014 IS 'Regra Fiscal Entrada XML';
COMMENT ON TABLE TBL0015 IS 'Loja';
COMMENT ON TABLE TBL0016 IS 'Vendedor';
COMMENT ON TABLE TBL0017 IS 'Adquirentes Cartao Credito';
COMMENT ON TABLE TBL0018 IS 'Bandeiras Cartao Credito';
COMMENT ON TABLE TBL0019 IS 'Promocao';
COMMENT ON TABLE TBL0020 IS 'Produtos Promocao';
COMMENT ON TABLE TBL0021 IS 'Forma Pagamento x Promocao';
COMMENT ON TABLE TBL0022 IS 'Orcamento';
COMMENT ON TABLE TBL0023 IS 'Produtos Orcamento';
COMMENT ON TABLE TBL0024 IS 'Notas Fiscais';
COMMENT ON TABLE TBL0025 IS 'Produtos Notas Fiscais';
COMMENT ON TABLE TBL0026 IS 'Forma Recebimento Notas Fiscais';
COMMENT ON TABLE TBL0027 IS 'Duplicatas Notas Fiscais';
COMMENT ON TABLE TBL0028 IS 'Duplicatas Recebidas';
COMMENT ON TABLE TBL0029 IS 'Forma Recebimento Duplicatas Recebidas';
COMMENT ON TABLE TBL0030 IS 'Status Situacao Cheque';
COMMENT ON TABLE TBL0031 IS 'Comprovante Venda Cartao de Credito';
COMMENT ON TABLE TBL0032 IS 'Parcelas Venda Cartao de Credito';
COMMENT ON TABLE TBL0033 IS 'Cheques';
COMMENT ON TABLE TBL0034 IS 'Recebimento Cheques';
COMMENT ON TABLE TBL0035 IS 'CFOP';
COMMENT ON TABLE TBL0036 IS 'CST_ICMS';
COMMENT ON TABLE TBL0037 IS 'CST PIS_COFINS';
COMMENT ON TABLE TBL0038 IS 'CST SIMPLES';
COMMENT ON TABLE TBL0039 IS 'Perfil Fiscal';
COMMENT ON TABLE TBL0040 IS 'Municipios';
COMMENT ON TABLE TBL0041 IS 'Unidades da Federacao';
COMMENT ON TABLE TBL0042 IS 'Paises';
COMMENT ON TABLE TBL0043 IS 'Marcas';
COMMENT ON TABLE TBL0044 IS 'Unidade de Produto';
COMMENT ON TABLE TBL0045 IS 'Boletos de Cobranca';
COMMENT ON TABLE TBL0046 IS 'Remessa Bancaria de Boletos';
COMMENT ON TABLE TBL0047 IS 'Carteira de Cobranca';
COMMENT ON TABLE TBL0048 IS 'Participante';
COMMENT ON TABLE TBL0049 IS 'Bancos';
COMMENT ON TABLE TBL0050 IS 'Agencia Bancaria';
COMMENT ON TABLE TBL0051 IS 'Conta Corrente Bancaria';
COMMENT ON TABLE TBL0052 IS 'Conta Corrente Participante';
COMMENT ON TABLE TBL0053 IS 'Operador Caixa';
COMMENT ON TABLE TBL0054 IS 'Movimentacao Caixa';
COMMENT ON TABLE TBL0055 IS 'Forma Lancamento Movimentacao do Caixa';
COMMENT ON TABLE TBL0056 IS 'TBL0056'; -- Descrição não fornecida, mantido o nome da tabela
COMMENT ON TABLE TBL0057 IS 'Locacao de Produto';
COMMENT ON TABLE TBL0058 IS 'CNAE';
COMMENT ON TABLE TBL0059 IS 'NCM';
COMMENT ON TABLE TBL0060 IS 'CEST';
COMMENT ON TABLE TBL0061 IS 'Tipos de Estoque';
COMMENT ON TABLE TBL0062 IS 'Categoria Produto';
COMMENT ON TABLE TBL0063 IS 'Natureza Operacao';
COMMENT ON TABLE TBL0064 IS 'Historico';
COMMENT ON TABLE TBL0065 IS 'Historico Contigencias';
COMMENT ON TABLE TBL0066 IS 'Impressora Nfe por Loja';
COMMENT ON TABLE TBL0067 IS 'Mensagem da Nfe por Loja';
COMMENT ON TABLE TBL0068 IS 'Documentos Participante (PDF,JPG,ETC)';
COMMENT ON TABLE TBL0069 IS 'CNAE x Participante';
COMMENT ON TABLE TBL0070 IS 'Pedido de Compra';
COMMENT ON TABLE TBL0071 IS 'Produto Pedido de Compra';
COMMENT ON TABLE TBL0072 IS 'Parcelas Pedido de Compra';
COMMENT ON TABLE TBL0073 IS 'Nota Fiscal x Pedido de Compra x Produto';
COMMENT ON TABLE TBL0074 IS 'Produto';
COMMENT ON TABLE TBL0075 IS 'Produto na Loja';
COMMENT ON TABLE TBL0076 IS 'Imagem do Produto';
COMMENT ON TABLE TBL0077 IS 'Preco Produto por Atacado';
COMMENT ON TABLE TBL0078 IS 'Historico Alteracao Produto';
COMMENT ON TABLE TBL0079 IS 'Historico Alteracao Participante';
COMMENT ON TABLE TBL0080 IS 'Produto x Participante (Fornecedores)';
COMMENT ON TABLE TBL0081 IS 'Produto x Fornecedor x XML';
COMMENT ON TABLE TBL0082 IS 'Produtos Alternativos - Somente referencia codigo do fabricante com codigo interno';
COMMENT ON TABLE TBL0083 IS 'Similaridade de Produtos';
COMMENT ON TABLE TBL0084 IS 'Estoque de Produtos';
COMMENT ON TABLE TBL0085 IS 'Movimentacao de Estoque';
COMMENT ON TABLE TBL0086 IS 'Saldo Diario Estoque';
COMMENT ON TABLE TBL0087 IS 'Saldo Diario Contas a Receber (Saldo Anterior + Entradas + Saidas + Saldo Atual)';
COMMENT ON TABLE TBL0088 IS 'Cupom de Desconto';
COMMENT ON TABLE TBL0089 IS 'Saldo Diario Caixa';
COMMENT ON TABLE TBL0090 IS 'Conta Contabil';
COMMENT ON TABLE TBL0091 IS 'Centro de Custo';
COMMENT ON TABLE TBL0092 IS 'Estoque de Produtos - Lote - Vencimento';
COMMENT ON TABLE TBL0093 IS 'Movimentacao Estoque Lote Produto';
COMMENT ON TABLE TBL0094 IS 'Nota Fiscal Referenciada';
COMMENT ON TABLE TBL0095 IS 'Cancelamento Nota Fiscal';
COMMENT ON TABLE TBL0096 IS 'Inutilizacao de Nfe';
COMMENT ON TABLE TBL0097 IS 'Adicoes Importacao Nota Fiscal Importacao';
COMMENT ON TABLE TBL0098 IS 'Contatos Parcipante (Telefone, Email)';
COMMENT ON TABLE TBL0099 IS 'Meta de Vendedor';
COMMENT ON TABLE TBL0100 IS 'Comprador';
COMMENT ON TABLE TBL0101 IS 'Extrato Bancario';
COMMENT ON TABLE TBL0102 IS 'Saldo Conta Corrente Bancaria';
COMMENT ON TABLE TBL0103 IS 'Feriados';
COMMENT ON TABLE TBL0104 IS 'Auditoria Estoque';
COMMENT ON TABLE TBL0105 IS 'Produtos Auditoria Estoque';
COMMENT ON TABLE TBL0106 IS 'Manifesto de Entrega';
COMMENT ON TABLE TBL0107 IS 'Romaneio de Embarque';
COMMENT ON TABLE TBL0108 IS 'Dispositivo Smart Pos';
COMMENT ON TABLE TBL0109 IS 'Funcionario';
COMMENT ON TABLE TBL0110 IS 'Transferencia entre Estoque';
COMMENT ON TABLE TBL0111 IS 'Produto da Transferencia entre Estoque';
COMMENT ON TABLE TBL0112 IS 'Faturas';
COMMENT ON TABLE TBL0113 IS 'Notas Fiscais da Fatura';
COMMENT ON TABLE TBL0114 IS 'Faturas x Duplicatas';
COMMENT ON TABLE TBL0115 IS 'Situacao do Produto';
COMMENT ON TABLE TBL0116 IS 'Lote de Baixa de Duplicatas';
COMMENT ON TABLE TBL0117 IS 'Lote x Recebimento Duplicatas';
COMMENT ON TABLE TBL0118 IS 'Lote x Forma de Recebimento da Duplicata';
COMMENT ON TABLE TBL0119 IS 'Tributacao MVA x Cest x Estado x NCM';

COMMIT;