Insert into MIGRATIONS(NOME_MIGRATION) values('003-2025-06-12-criacao-tabelas.slq');

CREATE TABLE TBL0001 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0001 PRIMARY KEY (ID)
);

CREATE TABLE TBL0002 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0002 PRIMARY KEY (ID)
);

CREATE TABLE TBL0003 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0003 PRIMARY KEY (ID)
);

CREATE TABLE TBL0004 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0004 PRIMARY KEY (ID)
);

CREATE TABLE TBL0005 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0005 PRIMARY KEY (ID)
);

CREATE TABLE TBL0006 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0006 PRIMARY KEY (ID)
);

CREATE TABLE TBL0007 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0007 PRIMARY KEY (ID)
);

CREATE TABLE TBL0008 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0008 PRIMARY KEY (ID)
);

CREATE TABLE TBL0009 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0009 PRIMARY KEY (ID)
);

CREATE TABLE TBL0010 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0010 PRIMARY KEY (ID)
);

CREATE TABLE TBL0011 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL011 PRIMARY KEY (ID)
);

CREATE TABLE TBL0012 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0012 PRIMARY KEY (ID)
);

CREATE TABLE TBL0013 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0013 PRIMARY KEY (ID)
);

CREATE TABLE TBL0014 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0014 PRIMARY KEY (ID)
);

CREATE TABLE TBL0015 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0015 PRIMARY KEY (ID)
);

CREATE TABLE TBL0016 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0016 PRIMARY KEY (ID)
);

CREATE TABLE TBL0017 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0017 PRIMARY KEY (ID)
);

CREATE TABLE TBL0018 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0018 PRIMARY KEY (ID)
);

CREATE TABLE TBL0019 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0019 PRIMARY KEY (ID)
);

CREATE TABLE TBL0020 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0020 PRIMARY KEY (ID)
);

CREATE TABLE TBL0021 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0021 PRIMARY KEY (ID)
);

CREATE TABLE TBL0022 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0022 PRIMARY KEY (ID)
);

CREATE TABLE TBL0023 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0023 PRIMARY KEY (ID)
);

CREATE TABLE TBL0024 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0024 PRIMARY KEY (ID)
);

CREATE TABLE TBL0025 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0025 PRIMARY KEY (ID)
);

CREATE TABLE TBL0026 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0026 PRIMARY KEY (ID)
);

CREATE TABLE TBL0027 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0027 PRIMARY KEY (ID)
);

CREATE TABLE TBL0028 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0028 PRIMARY KEY (ID)
);

CREATE TABLE TBL0029 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0029 PRIMARY KEY (ID)
);

CREATE TABLE TBL0030 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0030 PRIMARY KEY (ID)
);

CREATE TABLE TBL0031 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0031 PRIMARY KEY (ID)
);

CREATE TABLE TBL0032 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0032 PRIMARY KEY (ID)
);

CREATE TABLE TBL0033 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0033 PRIMARY KEY (ID)
);

CREATE TABLE TBL0034 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0034 PRIMARY KEY (ID)
);

CREATE TABLE TBL0035 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0035 PRIMARY KEY (ID)
);

CREATE TABLE TBL0036 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0036 PRIMARY KEY (ID)
);

CREATE TABLE TBL0037 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0037 PRIMARY KEY (ID)
);

CREATE TABLE TBL0038 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0038 PRIMARY KEY (ID)
);

CREATE TABLE TBL0039 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0039 PRIMARY KEY (ID)
);

CREATE TABLE TBL0040 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0040 PRIMARY KEY (ID)
);

CREATE TABLE TBL0041 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0041 PRIMARY KEY (ID)
);

CREATE TABLE TBL0042 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0042 PRIMARY KEY (ID)
);

CREATE TABLE TBL0043 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0043 PRIMARY KEY (ID)
);

CREATE TABLE TBL0044 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0044 PRIMARY KEY (ID)
);

CREATE TABLE TBL0045 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0045 PRIMARY KEY (ID)
);

CREATE TABLE TBL0046 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0046 PRIMARY KEY (ID)
);

CREATE TABLE TBL0047 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0047 PRIMARY KEY (ID)
);

CREATE TABLE TBL0048 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0048 PRIMARY KEY (ID)
);

CREATE TABLE TBL0049 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0049 PRIMARY KEY (ID)
);

CREATE TABLE TBL0050 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0050 PRIMARY KEY (ID)
);

CREATE TABLE TBL0051 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0051 PRIMARY KEY (ID)
);

CREATE TABLE TBL0052 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0052 PRIMARY KEY (ID)
);

CREATE TABLE TBL0053 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0053 PRIMARY KEY (ID)
);

CREATE TABLE TBL0054 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0054 PRIMARY KEY (ID)
);

CREATE TABLE TBL0055 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0055 PRIMARY KEY (ID)
);

CREATE TABLE TBL0056 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0056 PRIMARY KEY (ID)
);

CREATE TABLE TBL0057 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0057 PRIMARY KEY (ID)
);

CREATE TABLE TBL0058 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0058 PRIMARY KEY (ID)
);

CREATE TABLE TBL0059 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0059 PRIMARY KEY (ID)
);

CREATE TABLE TBL0060 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0060 PRIMARY KEY (ID)
);

CREATE TABLE TBL0061 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0061 PRIMARY KEY (ID)
);

CREATE TABLE TBL0062 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0062 PRIMARY KEY (ID)
);

CREATE TABLE TBL0063 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0063 PRIMARY KEY (ID)
);

CREATE TABLE TBL0064 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0064 PRIMARY KEY (ID)
);

CREATE TABLE TBL0065 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0065 PRIMARY KEY (ID)
);

CREATE TABLE TBL0066 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0066 PRIMARY KEY (ID)
);

CREATE TABLE TBL0067 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0067 PRIMARY KEY (ID)
);

CREATE TABLE TBL0068 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0068 PRIMARY KEY (ID)
);

CREATE TABLE TBL0069 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0069 PRIMARY KEY (ID)
);

CREATE TABLE TBL0070 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0070 PRIMARY KEY (ID)
);

CREATE TABLE TBL0071 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0071 PRIMARY KEY (ID)
);

CREATE TABLE TBL0072 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0072 PRIMARY KEY (ID)
);

CREATE TABLE TBL0073 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0073 PRIMARY KEY (ID)
);

CREATE TABLE TBL0074 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0074 PRIMARY KEY (ID)
);

CREATE TABLE TBL0075 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0075 PRIMARY KEY (ID)
);

CREATE TABLE TBL0076 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0076 PRIMARY KEY (ID)
);

CREATE TABLE TBL0077 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0077 PRIMARY KEY (ID)
);

CREATE TABLE TBL0078 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0078 PRIMARY KEY (ID)
);

CREATE TABLE TBL0079 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0079 PRIMARY KEY (ID)
);

CREATE TABLE TBL0080 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0080 PRIMARY KEY (ID)
);

CREATE TABLE TBL0081 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0081 PRIMARY KEY (ID)
);

CREATE TABLE TBL0082 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0082 PRIMARY KEY (ID)
);

CREATE TABLE TBL0083 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0083 PRIMARY KEY (ID)
);

CREATE TABLE TBL0084 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0084 PRIMARY KEY (ID)
);

CREATE TABLE TBL0085 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0085 PRIMARY KEY (ID)
);

CREATE TABLE TBL0086 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0086 PRIMARY KEY (ID)
);

CREATE TABLE TBL0087 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0087 PRIMARY KEY (ID)
);

CREATE TABLE TBL0088 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0088 PRIMARY KEY (ID)
);

CREATE TABLE TBL0089 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0089 PRIMARY KEY (ID)
);

CREATE TABLE TBL0090 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0090 PRIMARY KEY (ID)
);

CREATE TABLE TBL0091 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0091 PRIMARY KEY (ID)
);

CREATE TABLE TBL0092 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0092 PRIMARY KEY (ID)
);

CREATE TABLE TBL0093 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0093 PRIMARY KEY (ID)
);

CREATE TABLE TBL0094 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0094 PRIMARY KEY (ID)
);

CREATE TABLE TBL0095 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0095 PRIMARY KEY (ID)
);

CREATE TABLE TBL0096 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0096 PRIMARY KEY (ID)
);

CREATE TABLE TBL0097 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0097 PRIMARY KEY (ID)
);

CREATE TABLE TBL0098 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0098 PRIMARY KEY (ID)
);

CREATE TABLE TBL0099 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0099 PRIMARY KEY (ID)
);

CREATE TABLE TBL0100 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0100 PRIMARY KEY (ID)
);

CREATE TABLE TBL0101 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0101 PRIMARY KEY (ID)
);

CREATE TABLE TBL0102 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0102 PRIMARY KEY (ID)
);

CREATE TABLE TBL0103 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0103 PRIMARY KEY (ID)
);

CREATE TABLE TBL0104 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0104 PRIMARY KEY (ID)
);

CREATE TABLE TBL0105 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0105 PRIMARY KEY (ID)
);

CREATE TABLE TBL0106 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0106 PRIMARY KEY (ID)
);

CREATE TABLE TBL0107 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0107 PRIMARY KEY (ID)
);

CREATE TABLE TBL0108 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0108 PRIMARY KEY (ID)
);

CREATE TABLE TBL0109 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0109 PRIMARY KEY (ID)
);

CREATE TABLE TBL0110 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0110 PRIMARY KEY (ID)
);

CREATE TABLE TBL0111 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0111 PRIMARY KEY (ID)
);

CREATE TABLE TBL0112 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0112 PRIMARY KEY (ID)
);

CREATE TABLE TBL0113 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0113 PRIMARY KEY (ID)
);

CREATE TABLE TBL0114 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0114 PRIMARY KEY (ID)
);

CREATE TABLE TBL0115 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0115 PRIMARY KEY (ID)
);

CREATE TABLE TBL0116 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0116 PRIMARY KEY (ID)
);

CREATE TABLE TBL0117 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0117 PRIMARY KEY (ID)
);

CREATE TABLE TBL0118 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0118 PRIMARY KEY (ID)
);

CREATE TABLE TBL0119 (
  ID D_ID NOT NULL,
  DT_CREATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_CREATE D_USUARIO,
  DT_UPDATE D_AGORA DEFAULT CURRENT_TIMESTAMP,
  USER_UPDATE D_USUARIO,
  DT_DELETED D_AGORA,
  USER_DELETED D_USUARIO,
  DELETED D_STA_INT DEFAULT 0,
  ATIVO D_STA_INT DEFAULT 0, -- VIRGULA ADICIONADA AQUI
  CONSTRAINT PK_TBL0119 PRIMARY KEY (ID)
);

COMMIT;
